### ISSUE TITLE
添加：用 vimdiff 格式展示修改

### ISSUE THREAD

**Issue by mefengl** [wuchangming/chatgpt-prompt-engineer-handbook#1]
ChatGPT有时会做些很小的refactor，不容易知道在哪里，加上这个提示后，就会生成vimdiff的格式（我觉得这个格式也不是很直观，但一时之间找不到更好的）

使用是：
重构此代码，然后以vimdiff格式显示更改的内容，并解释更改的内容：
英文：
Refactor this code, then show what's changed in vimdiff format and explain what's changed:

**Comment by wuchangming** [comment]
感觉效果不是很好

**Comment by mefengl** [comment]
![image](https://user-images.githubusercontent.com/71683364/206703964-bc299700-316c-4629-97f0-12421a68d357.png)
这样的效果对我来说就很好了，毕竟git diff看习惯了。。。
只是一种思路吧，感觉重构的话，知道它改了哪里还是蛮重要的

**Comment by mefengl** [comment]
用中文试了下，第一次没有vimdiff，第二次是这样的效果

![image](https://user-images.githubusercontent.com/71683364/206707036-de9ff885-323e-4b81-aaaf-1edd0082488d.png)

第三次要好一点：

![image](https://user-images.githubusercontent.com/71683364/206707538-279d0455-646b-4d8d-981b-207d78d67b18.png)

**Comment by wuchangming** [comment]
@mefengl ，确实用中文不太行，英文还挺不错的
