### ISSUE TITLE
可以用ChatGPT生成更多技巧🤯

### ISSUE THREAD

**Issue by mefengl** [wuchangming/chatgpt-prompt-engineer-handbook#3]
![image](https://user-images.githubusercontent.com/71683364/206631293-55a32d9e-260c-487b-9723-011313fdaa1c.png)

**Comment by gaoryrt** [comment]
厉害了，能问出这样的问题……

**Comment by wuchangming** [comment]
@mefengl  你这个思路不错，可以让 ChatGPT 自己说他能干什么

**Comment by luo-zi** [comment]
在我的使用中发现, 对chatGPT要求使用xx语言实现时可以通过这样的文本来引导其写法:
 - 请使用索引
 - 请使用xxxxxx这种思路
 - 在生成代码后请进行代码逻辑检查和路径覆盖测试, 若存在与题意不符则修正代码
 - 仅输出JS代码 (这个个人认为非常有用, 生成前端网页的代码时可以避免大量输出)

**Comment by mefengl** [comment]
@wuchangming 这个要不要加到文档里，或者closed掉

**Comment by wuchangming** [comment]
@mefengl ，我觉得可以总结进来
